# Stable
newline_style = "Unix"
use_field_init_shorthand = true

# Unstable
unstable_features = true
version = "One"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
wrap_comments = true
